version: "3.2"

services:
  dev:
    image: ${IMAGE}:${BUILD_ID}
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: ${LIVE_HOSTNAME}
        com.docker.lb.port: 80
        com.docker.lb.network: testapp-network
        service-status: standby
    networks:
      - testapp-network

networks:
  testapp-network:
    driver: overlay
